CREATE TABLE IF NOT EXISTS MASTER_APP_DATA(
appid INTEGER PRIMARY KEY AUTOINCREMENT,
appDate DATE
);

CREATE TABLE IF NOT EXISTS AUDIT_LOG(
auditid INTEGER PRIMARY KEY AUTOINCREMENT,
deviceID TEXT,
username TEXT,
Timestamp TEXT,
auditDate DATE DEFAULT CURRENT_DATE,
service TEXT,
action TEXT,
value BLOB
);

CREATE TABLE IF NOT EXISTS ERROR_LOG(
errorId INTEGER PRIMARY KEY AUTOINCREMENT,
deviceID TEXT,
username TEXT,
Timestamp TEXT,
auditDate DATE DEFAULT CURRENT_DATE,
errorDesc BLOB,
pageName TEXT
);
